name: Pyramid_m2
root_dir: "dataset/V2V4Real/train"
validate_dir: "dataset/V2V4Real/validate"
test_dir: "dataset/V2V4Real/test"

yaml_parsers: 
  m0: "load_general_params"
  m4: "load_general_params"

train_params:
  batch_size: &batch_size 2
  epoches: 5
  eval_freq: 1
  save_freq: 1
  max_cav: 2

comm_range: 70
input_source: ['lidar', 'camera', 'depth']
label_type: 'lidar'
cav_lidar_range: &cav_lidar [-102.4, -51.2, -3, 102.4, 51.2, 1] 

add_data_extension: ['bev_visibility.png']

heter:
  assignment_path: "opencood/logs/heter_modality_assign/opv2v_4modality.json" 
  ego_modality: &ego_modality "m4"
  protocol_modality: &protocol_modality "m0"
  mapping_dict:
    m1: m4
    m2: m4
    m3: m4
    m4: m4
  modality_setting:
    m0:
      sensor_type: &sensor_type_m0 'lidar'
      core_method: &core_method_m0 "point_pillar"

      # lidar requires preprocess
      preprocess:
        # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
        core_method: 'SpVoxelPreprocessor'
        args:
          voxel_size: &voxel_size_m0 [0.4, 0.4, 4]
          max_points_per_voxel: 32
          max_voxel_train: 32000
          max_voxel_test: 70000
        # lidar range for each individual cav.
        cav_lidar_range: &cav_lidar_m0 [-102.4, -51.2, -3, 102.4, 51.2, 1]

      postprocess:
        core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
        gt_range: *cav_lidar_m0
        voxel_size: *voxel_size_m0
        anchor_args:
          cav_lidar_range: *cav_lidar_m0
          l: 3.9
          w: 1.6
          h: 1.56
          r: &anchor_yaw_m0 [0, 90]
          feature_stride: 2
          num: &anchor_num_m0 2
        target_args:
          pos_threshold: 0.6
          neg_threshold: 0.45
          score_threshold: 0.2
        order: 'hwl' # hwl or lwh
        max_num: 150 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
        nms_thresh: 0.15
        dir_args: &dir_args_m0
          dir_offset: 0.7853
          num_bins: 2
          anchor_yaw: *anchor_yaw_m0
    m4:
      sensor_type: &sensor_type_m4 'lidar'
      core_method: &core_method_m4 "point_pillar"

      # lidar requires preprocess
      preprocess:
        # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
        core_method: 'SpVoxelPreprocessor'
        args:
          voxel_size: &voxel_size_m4 [0.4, 0.4, 4]
          max_points_per_voxel: 32
          max_voxel_train: 32000
          max_voxel_test: 70000
        # lidar range for each individual cav.
        cav_lidar_range: &cav_lidar_m4 [-102.4, -51.2, -3, 102.4, 51.2, 1]

      postprocess:
        core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
        gt_range: *cav_lidar 
        voxel_size: *voxel_size_m4
        anchor_args:
          cav_lidar_range: *cav_lidar
          l: 3.9
          w: 1.6
          h: 1.56
          r: &anchor_yaw_m4 [0, 90]
          feature_stride: 2
          num: &anchor_num_m4 2
        target_args:
          pos_threshold: 0.6
          neg_threshold: 0.45
          score_threshold: 0.2
        order: 'hwl' # hwl or lwh
        max_num: 150 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
        nms_thresh: 0.15
        dir_args: &dir_args_m4
          dir_offset: 0.7853
          num_bins: 2
          anchor_yaw: *anchor_yaw_m4


fusion:
  core_method: 'intermediateheteradapter'
  dataset: 'opv2v'
  args: 
    proj_first: false
    grid_conf: None # place-holder
    data_aug_conf: None # place-holder


# model related
model:
  core_method: collab_w_adapter
  args:
    stage: train_adapter_w_output
    crop_to_visible: true
    supervise_single: true
    ego_modality: *ego_modality
    protocol_modality: *protocol_modality
    heterogeneous: true

    m0:
      core_method: *core_method_m0
      sensor_type: *sensor_type_m0
      lidar_range: *cav_lidar_m0

      encoder_args:
        voxel_size: *voxel_size_m0
        lidar_range: *cav_lidar_m0
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters: [64]
        point_pillar_scatter:
          num_features: 64

      backbone_args:
        layer_nums: [3]
        layer_strides: [2]
        num_filters: [64]
  
      aligner_args:
        core_method: identity

      fusion_method: pyramid

      fusion_backbone: 
        resnext: true
        layer_nums: [3, 5, 8]
        layer_strides: [1, 2, 2]
        num_filters: [64, 128, 256]
        upsample_strides: [1, 2, 4]
        num_upsample_filter: [128, 128, 128]
        anchor_number: *anchor_num_m0

      shrink_header: 
        kernal_size: [ 3 ]
        stride: [ 1 ]
        padding: [ 1 ]
        dim: [ 256 ]
        input_dim: 384 # 128 * 3

      in_head: 256
      anchor_number: *anchor_num_m0
      dir_args: *dir_args_m0
        
    m4:
      core_method: *core_method_m4
      sensor_type: *sensor_type_m4
      lidar_range: *cav_lidar_m4

      encoder_args:
        voxel_size: *voxel_size_m4
        lidar_range: *cav_lidar_m4
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters: [64]
        point_pillar_scatter:
          num_features: 64

      backbone_args:
        layer_nums: [3]
        layer_strides: [2]
        num_filters: [64]
  
      aligner_args:
        core_method: identity

      fusion_method: pyramid

      fusion_backbone: 
        resnext: true
        layer_nums: [3, 5, 8]
        layer_strides: [1, 2, 2]
        num_filters: [64, 128, 256]
        upsample_strides: [1, 2, 4]
        num_upsample_filter: [128, 128, 128]
        anchor_number: *anchor_num_m4

      shrink_header: 
        kernal_size: [ 3 ]
        stride: [ 1 ]
        padding: [ 1 ]
        dim: [ 256 ]
        input_dim: 384 # 128 * 3

      in_head: 256
      anchor_number: *anchor_num_m4
      dir_args: *dir_args_m4

      adapter:
        core_method: adapterconvnext
        args:
          in_channels: 64
          out_channels: 64
          in_cav_lidar_range: *cav_lidar_m4
          out_cav_lidar_range: *cav_lidar_m4
          in_feature_shape: [128, 256]
          out_feature_shape: [128, 256]
          submodule_args:
            num_of_blocks: 3
            dim: 64

      reverter:
        core_method: adapterconvnext
        args:
          in_channels: 64
          out_channels: 64
          in_cav_lidar_range: *cav_lidar_m4
          out_cav_lidar_range: *cav_lidar_m4
          in_feature_shape: [128, 256]
          out_feature_shape: [128, 256]
          submodule_args:
            num_of_blocks: 3
            dim: 64

loss_adapter:
  core_method: adapter_loss
  args:
    alpha_P2M: 9.0
    alpha_M2P2M: 1.0
    alpha_M2P: 10.0

loss:
  m0:
    core_method: point_pillar_pyramid_loss
    args:
      pos_cls_weight: 2.0
      cls:
        type: 'SigmoidFocalLoss'
        alpha: 0.25
        gamma: 2.0
        weight: 1.0
      reg:
        type: 'WeightedSmoothL1Loss'
        sigma: 3.0
        codewise: true
        weight: 2.0
      dir:
        type: 'WeightedSoftmaxClassificationLoss'
        weight: 0.2
        args: *dir_args_m0
      depth:
        weight: 1.0
      pyramid:
        relative_downsample: [1, 2, 4]
        weight: [0.4, 0.2, 0.1]
  m4:
    core_method: point_pillar_pyramid_loss
    args:
      pos_cls_weight: 2.0
      cls:
        type: 'SigmoidFocalLoss'
        alpha: 0.25
        gamma: 2.0
        weight: 1.0
      reg:
        type: 'WeightedSmoothL1Loss'
        sigma: 3.0
        codewise: true
        weight: 2.0
      dir:
        type: 'WeightedSoftmaxClassificationLoss'
        weight: 0.2
        args: *dir_args_m4
      depth:
        weight: 1.0
      pyramid:
        relative_downsample: [1, 2, 4]
        weight: [0.4, 0.2, 0.1]



optimizer:
  core_method: Adam
  lr: 0.01
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [1, 3, 4]


